### ISSUE TITLE
Danh sách yêu cầu về user

### ISSUE THREAD

**Issue by quangvung** [quangvung/ProjectAppDatBan#1]
Triển khai lấy yêu cầu của khách hàng

**Comment by quangvung** [comment]
Vấn đề về lấy yêu cầu chưa gặp được khách hàng do công ty đóng cửa nghỉ lễ

**Comment by Huynh-Nhi** [comment]
-việc cần làm: gặp khách hàng để lấy yêu cầu
-input: từng yêu cầu khách hàng đặt ra
-output: danh sách các yêu cầu của khách hàng
[DSYeuCauKhachHang.pdf](https://github.com/quangvung/ProjectAppDatBan/files/6133841/DSYeuCauKhachHang.pdf)
