### ISSUE TITLE
Mẫu kiến trúc MVC và vẽ thành phần chi tiết về kiên trúc hệ thống phần mềm

### ISSUE THREAD

**Issue by jay-pro** [quangvung/ProjectAppDatBan#11]
Mỗi nhóm chọn mẫu kiến trúc và vẽ thành phần chi tiết về kiên trúc hệ thống phần mềm của đề tài cuối kỳ.
Một bạn trong nhóm đại diện nộp sơ đồ này (dạng pdf/ ảnh)

**Comment by Huynh-Nhi** [comment]
- Chọn mẫu kiến trúc: MVC
- Vẽ thành phần chi tiết về kiên trúc hệ thống phần mềm của đề tài cuối kỳ
[SoDoKienTrucHeThong.pdf](https://github.com/quangvung/ProjectAppDatBan/files/6254233/SoDoKienTrucHeThong.pdf)
