### ISSUE TITLE
File README.txt hướng dẫn cách thực thi code, yêu cầu thư viện cần cài đặt 

### ISSUE THREAD

**Issue by jay-pro** [quangvung/ProjectAppDatBan#18]

**Comment by quangvung** [comment]
[README.txt](https://github.com/quangvung/ProjectAppDatBan/files/6352154/README.txt)

**Comment by quangvung** [comment]
H
[README.txt](https://github.com/quangvung/ProjectAppDatBan/files/6352205/README.txt)
ướng dẫn cách thực thi code, yêu cầu thư viện cần cài đặt

**Comment by quangvung** [comment]
Hướng dẫn cách thực thi code, yêu cầu thư viện cần cài đặt

[README.txt](https://github.com/quangvung/ProjectAppDatBan/files/6352207/README.txt)
