### ISSUE TITLE
User của phần mềm

### ISSUE THREAD

**Issue by jay-pro** [quangvung/ProjectAppDatBan#2]
<Mô tả...>

**Comment by jay-pro** [comment]
<Phần này của Hà Nhi>
<add file nếu có>

**Comment by jay-pro** [comment]
-việc cần làm: các users phần mềm
-input: các users phần mềm
-output: bảng phân tích gồm các cột STT, users phần mềm, mô tả
[UserPhanMem.pdf](https://github.com/quangvung/ProjectAppDatBan/files/6154482/UserPhanMem.pdf)

**Comment by quangvung** [comment]
Đã duyệt phần của Bùi Hà Nhi _ 18110168.
