### ISSUE TITLE
Yêu cầu chức năng

### ISSUE THREAD

**Issue by jay-pro** [quangvung/ProjectAppDatBan#3]
<Mô tả...>

**Comment by Huynh-Nhi** [comment]
<Đã xem>

**Comment by Huynh-Nhi** [comment]
-việc cần làm: phân tích yêu cầu người dùng và yêu cầu hệ thống
-input: các chức năng của hệ thống
-output: bảng phân tích gồm các cột STT, chức năng,
[YeuCauChucNang.pdf](https://github.com/quangvung/ProjectAppDatBan/files/6154180/YeuCauChucNang.pdf)
 yêu cầu người dùng và yêu cầu hệ thống

**Comment by Huynh-Nhi** [comment]
-việc cần làm: phân tích yêu cầu người dùng và yêu cầu hệ thống
-input: các chức năng của hệ thống
-output: bảng phân tích gồm các cột STT, chức năng, yêu cầu người dùng và yêu cầu hệ thống
[YeuCauChucNang.pdf](https://github.com/quangvung/ProjectAppDatBan/files/6154187/YeuCauChucNang.pdf)

**Comment by jay-pro** [comment]
Đã duyệt phần của Huỳnh Trần Thảo Nhi _ 18110169.
