### ISSUE TITLE
Yêu cầu phi chức năng

### ISSUE THREAD

**Issue by jay-pro** [quangvung/ProjectAppDatBan#4]
<Mô tả...>

**Comment by quangvung** [comment]
-việc cần làm: các yêu cầu phi chức năng của hệ thống
-input: các yêu cầu phi chức năng của hệ thống
-output: bảng phân tích gồm các cột STT, yêu cầu phi chức năng của hệ thống
[YeuCauPhiChucNang.pdf](https://github.com/quangvung/ProjectAppDatBan/files/6154428/YeuCauPhiChucNang.pdf)

**Comment by Huynh-Nhi** [comment]
Đã duyệt phần của Nguyễn Quang Vũ - 1811241
