### ISSUE TITLE
1. Sử dụng ngôn ngữ có cấu trúc

### ISSUE THREAD

**Issue by jay-pro** [quangvung/ProjectAppDatBan#5]
![Sửdụngngônngữcócấutrúc](https://user-images.githubusercontent.com/60065901/111856212-c4b29800-895b-11eb-91ff-e315631c2960.png)

**Comment by Huynh-Nhi** [comment]
-Việc cần làm: sử dụng ngôn ngữ có cấu trúc đặc tả yêu cầu phần mềm 
-Input: Ds các yêu cầu chức năng đã thực hiện ngày 17/3/2021
-Output: các bảng có cấu trúc giống nhau gồm các cột( Function, Description, Inputs, Source, Output, Destination, Action, Requirements, Pre-Condition, Post-Condition, Side effects  ) cho từng chức năng
[SdNgonNguCoCauTruc.pdf](https://github.com/quangvung/ProjectAppDatBan/files/6194330/SdNgonNguCoCauTruc.pdf)

**Comment by jay-pro** [comment]
(Bùi Hà Nhi _ 18110168)
Đã duyệt.

**Comment by quangvung** [comment]
Nguyễn Quang Vũ_18110241
Đã duyệt.
