### ISSUE TITLE
2. Sử dụng bảng (mô tả action trong cách 1)

### ISSUE THREAD

**Issue by jay-pro** [quangvung/ProjectAppDatBan#6]
![Sửdụngbảng(môtảactiontrongcách1)](https://user-images.githubusercontent.com/60065901/111856352-b153fc80-895c-11eb-9041-fd916361efaf.png)

**Comment by jay-pro** [comment]
(Bùi Hà Nhi - 18110168)
- Việc cần làm: Đặc tả yêu cầu phần mềm theo cách 2 (Sử dụng bảng)
- Input: liệt kê các điều kiện, action từ cách 1 (Sử dụng ngôn ngữ có cấu trúc) của từng chức năng (Yêu cầu chức năng ở Milestone 2)
- Ouput: các bảng phân tích gồm 2 cột Condition và Action
[Milestone3_Sử Dụng Bảng.docx](https://github.com/quangvung/ProjectAppDatBan/files/6194251/Milestone3_S.D.ng.B.ng.docx)

**Comment by Huynh-Nhi** [comment]
Huỳnh Trần Thảo Nhi-18110169 đã duyệt

**Comment by quangvung** [comment]
Nguyễn Quang Vũ_18110241
Đã duyệt.
