### ISSUE TITLE
3. Sử dụng sơ đồ usercase

### ISSUE THREAD

**Issue by jay-pro** [quangvung/ProjectAppDatBan#7]
(Ảnh minh họa trên fhq)

**Comment by quangvung** [comment]
Nguyễn Quang Vũ_18110241
- Việc cần làm: phân tích chức năng của user rồi vẽ
[Milestone3_Sử-Dụng-UserCase-.pdf](https://github.com/quangvung/ProjectAppDatBan/files/6194302/Milestone3_S.-D.ng-UserCase-.pdf)

- Input: Entity class, Control class
- Output: Sơ đồ user case

**Comment by Huynh-Nhi** [comment]
Huỳnh Trần Thảo Nhi- 18110169 đã duyệt

**Comment by jay-pro** [comment]
(Bùi Hà Nhi _ 18110168)
Đã duyệt.
