### ISSUE TITLE
2. Sequence Diagram

### ISSUE THREAD

**Issue by jay-pro** [quangvung/ProjectAppDatBan#9]

**Comment by Huynh-Nhi** [comment]
Việc cần làm: Thiết kế lược đồ Sequence Diagram 
Input: Bảng mô tả chức năng
Ouput: Lược đồ Sequence Diagram 
[ThietKeLuocDo_Sequence-Diagram.pdf](https://github.com/quangvung/ProjectAppDatBan/files/6251865/ThietKeLuocDo_Sequence-Diagram.pdf)
